### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#11]
# Dropdown
A Dropdown is a selection component composed of a button and a list of options.

**Tasks:**
- [ ] Dropdown
  - [ ] variants: see more about variants in the storybook [here](https://react.fluentui.dev/?path=/docs/components-dropdown--default#appearance).
  - [ ] options: options are defined as JSX children, and can include nested elements or other components.
    - [ ] custom: options and OptionGroups can be extended and customized.
    - [ ] multiselec: Dropdown supports multiselect, and options within a multiselect will display checkbox icons.
  - [ ] behavior: follow behavior specified [here](https://react.fluentui.dev/?path=/docs/components-dropdown--default)
