### ISSUE TITLE
InfoLabel

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#12]
InfoLabel
An InfoLabel is a Label with an InfoButton at the end, properly handling layout and accessibility properties.

**Tasks:**
- [ ] InfoLabel
  - [ ] required: when marked required, the indicator asterisk is placed before the InfoButton.
  - [ ] sizes: InfoLabel's size prop affects the size of the Label and InfoButton. The default size is medium.
  - [ ] behavior: follow behavior specified [here](https://react.fluentui.dev/?path=/docs/components-infolabel--default)
