### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#13]
# Input
Input allows the user to enter and edit text.

**Tasks:**
- [ ] Input
  - [ ] content: an input can have elements such as an icon or a button before or after the entered text (inside the input).
  - [ ] disabled: an input can be disabled.
  - [ ] variants: see more about variants in the storybook [here](https://react.fluentui.dev/?path=/docs/components-input--default#appearance).
  - [ ] behavior: follow behavior specified [here](https://react.fluentui.dev/?path=/docs/components-input--default)
