### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#3]
# Button 
A button triggers an action or event when activated.

**Tasks:**
- [ ] Button
  - [ ] shape: a button can be rounded, circular, or square.
  - [ ] variants: see more about variants in the storybook [here](https://react.fluentui.dev/iframe.htmlviewMode=docs&id=components-button-button--default#appearance).
  - [ ] icon: expand icon slot rendered before (or after) children content in heading.
  - [ ] size: a button can be small, medium and large size. Default being medium.
  - [ ] loading: a button can simulate a convincing loading state.

**Comment by Willienn** [comment]
### Not doing "as prop" for now
Adding "as prop" is relatively simple when the component isn't a forwardRef component. I haven't yet found a way to do this, but I'm still looking.

### References:
https://stackoverflow.com/a/77176708/19266672
https://www.robinwieruch.de/react-as-prop/
https://www.christianvm.dev/blog/react-as-prop

### Extra notes
Just for clarification, while it "works" it broken the typescript entirely.
