### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#4]
# Card 
A card is a container that holds information and actions related to a single concept or object, like a document or a contact.

**Tasks:**
- [ ] Card
  - [ ] shape: a card can be either vertically (by default) or horizontally.
  - [ ] variants: see more about variants in the storybook [here](https://react.fluentui.dev/?path=/docs/components-card-card--default#appearance).
  - [ ] selectable: card can be selectable.
