### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#5]
# Checkbox
Checkboxes give people a way to select one or more items from a group, or switch between two mutually exclusive options.

**Tasks:**
- [ ] Card
  - [ ] controled: a checkbox can be initially checked using defaultChecked, or controlled via the checked property.
  - [ ] disabled: a checkbox can be disabled
  - [ ] required: a checkbox can be marked as required
  - [ ] label position: label can be positioned before the checkbox
