### ISSUE TITLE
Combobox

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#6]
# Combobox
A combobox (Combobox) combines a text field and a dropdown giving people a way to select an option from a list or enter their own choice.

**Tasks:**

- [ ] Combobox
  - [ ] options: options are defined as JSX children, and can include nested elements or other components.
  - [ ] controlled: a Combobox may have controlled selection and value
  - [ ] multiselect: combobox can have multiselect 
  - [ ] variants: see more about variants in the storybook [here](https://react.fluentui.dev/iframe.htmlviewMode=docs&id=components-button-button--default#appearance).

**Comment by Willienn** [comment]
All 3 functionalities that remains will demand too much time and complexity to the component
