### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#7]
# Dialog
Dialog is a window overlaid on either the primary window or another dialog window.

**Tasks:**
- [ ] Checkbox
  - [ ] non-modal: A non-modal Dialog by default presents no backdrop, allowing elements outside of the Dialog to be interacted with.
  - [ ] alert: An alert Dialog is a modal dialog that interrupts the user's workflow to communicate an important message and acquire a response. 
  - [ ] behavior: follow behavior specified [here](https://react.fluentui.dev/?path=/docs/components-dialog--default)

**Comment by Willienn** [comment]
Further investigation needed! Hydration error persists despite following documentation.
