### ISSUE TITLE
Divider

### ISSUE THREAD

**Issue by Willienn** [grbtec/gbt-fluent2-web#8]
# Divider
A divider visually separates two pieces of content.

**Tasks:**
- [ ] Divider
  - [ ] orientation: A divider can vertically separate two pieces of content.
  - [ ] variants: see more about variants in the storybook [here](https://react.fluentui.dev/iframe.htmlviewMode=docs&id=components-button-button--default#appearance).
  - [ ] content-position: the label associated with the divider can be aligned at the start, center, or end of the divider line.
